channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - conda-forge::python_abi
  - conda-forge::python=3.8
  - conda-forge::pytables
  - conda-forge::fastparquet
  - conda-forge::astropy
  - conda-forge::catboost
  - conda-forge::colorcet
  - conda-forge::cmasher
  - conda-forge::schemdraw
  - pip:
      - "numpy==1.20.3"
      - "matplotlib==3.6.1"
      - "pandas==1.4.4"
      - "scikit-learn==0.23.2"
      - chainconsumer
      - lightgbm
      - "xgboost==1.5.1"
      - "pycaret==2.3.10"
      - fasttreeshap
