channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - "numpy==1.20.3"
      - "matplotlib==3.6.1"
      - fastparquet
      - "pandas==1.4.4"
      - "scikit-learn==0.23.2"
      - lightgbm
      - "xgboost==1.5.1"
      - "pycaret==2.3.10"
      - fasttreeshap
  - pytables
  - astropy
  - catboost
  - colorcet
  - cmasher
  - schemdraw
