channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - conda-forge::python_abi
  - conda-forge::python=3.8
  - conda-forge::numpy=1.20.3
  - scikit-learn=0.23.2
  - conda-forge::matplotlib=3.6.1
  - conda-forge::pytables
  - conda-forge::pandas=1.4.4
  - conda-forge::astropy
  - conda-forge::catboost
  - conda-forge::colorcet
  - conda-forge::cmasher
  - conda-forge::schemdraw
  - pip:
      - chainconsumer
      - lightgbm
      - "xgboost==1.5.1"
      - "pycaret==2.3.10"
      - fasttreeshap
